Memasukan library

In [6]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

 Baca file CSV dengan delimiter

In [7]:
df = pd.read_csv("matdis.csv", sep=";")

#Kemudian Rename kolom biar lebih ringkas
df = df.rename(columns={
    'ADIL DAN AMANAH': 'A',
    'SUKA MEMBANTU': 'B',
    'NYAMBUNG KALAU NGOROL': 'C',
    'ASYIK DAN MENARIK': 'D'})

Karena di data ada nilai kosong (NaN) → Python tidak bisa langsung dipakai untuk perhitungan matematis.Sehingga df.fillna(0) mengganti semua NaN jadi 0.Tujuannya supaya tidak error waktu dihitung korelasi, similarity, dsb.

In [8]:
#Bersihkan data NaN (kosong)
df = df.fillna(0)
#Ambil nilai A–D sebagai matriks
nilai = df[['A','B','C','D']].to_numpy()

In [9]:
#Matriks Kovarian & Korelasi
cov_mat = np.cov(nilai, rowvar=False, ddof=1)
corr_mat = np.corrcoef(nilai, rowvar=False)

print("=== Matriks Kovarian ===")
print(cov_mat)

print("\n=== Matriks Korelasi ===")
print(corr_mat)

=== Matriks Kovarian ===
[[0.00765557 0.00789801 0.00772034 0.00768563]
 [0.00789801 0.00836052 0.00803267 0.00800823]
 [0.00772034 0.00803267 0.0080655  0.0078506 ]
 [0.00768563 0.00800823 0.0078506  0.00787601]]

=== Matriks Korelasi ===
[[1.         0.98721559 0.98249809 0.98977746]
 [0.98721559 1.         0.97819987 0.9868849 ]
 [0.98249809 0.97819987 1.         0.98499445]
 [0.98977746 0.9868849  0.98499445 1.        ]]


Hasilnya menunjukkan bahwa penyebaran nilai antar aspek cukup seragam dan semua aspek penilaian memiliki korelasi yang sangat kuat di atas 0,97, yang berarti mahasiswa yang mendapat nilai tinggi pada satu aspek cenderung juga tinggi pada aspek lainnya, jadi penilaian antar aspek bersifat konsisten.


In [ ]:
#Cosine Similarity antar siswa
cosine_sim = cosine_similarity(nilai)
cosine_df = pd.DataFrame(
    cosine_sim,
    index=df['NAMA'],
    columns=df['NAMA']
)
print("\n=== Cosine Similarity antar siswa ===")
print(cosine_df)


=== Cosine Similarity antar siswa ===
NAMA                     MADINA HEDY ALIFANTI  MARIA DWI KURNIASIH  \
NAMA                                                                 
MADINA HEDY ALIFANTI                 1.000000             0.993631   
MARIA DWI KURNIASIH                  0.993631             1.000000   
ADINDA PUTRI RACHMAWATI              0.977117             0.973243   
AQUINA SYABITA                       0.997386             0.986099   
VARID PUTRA PRATAMA                  0.994175             0.995041   
...                                       ...                  ...   
0                                    0.000000             0.000000   
0                                    0.000000             0.000000   
0                                    0.000000             0.000000   
0                                    0.000000             0.000000   
0                                    0.000000             0.000000   

NAMA                     ADINDA PUTRI RACHMAWATI  

Cosine similarity menunjukkan bahwa hampir semua siswa memiliki pola jawaban yang sangat mirip, dengan tingkat kesamaan di atas 97%,berarti penilaian antar siswa cenderung homogen dan konsisten. Adanya nilai 0 bukan menunjukkan perbedaan, melainkan berasal dari data kosong yang ikut terbaca. Dengan demikian, dapat disimpulkan bahwa mayoritas siswa memiliki keseragaman dalam pola penilaian.

In [ ]:
#Cari Top 4 Mahasiswa berdasarkan total skor A–D
df['TOTAL'] = df[['A','B','C','D']].sum(axis=1)
top4 = df.nlargest(4, 'TOTAL')[['NPM','NAMA','TOTAL']]

print("\n=== Top 4 Mahasiswa ===")
print(top4)


=== Top 4 Mahasiswa ===
            NPM                     NAMA  TOTAL
7  2.408301e+10  HIZKIA SAMHAN REZAYOSHI    3.9
4  2.408301e+10      VARID PUTRA PRATAMA    3.4
1  2.408301e+10      MARIA DWI KURNIASIH    3.3
9  2.408301e+10   Yohanes Olvin Jun Sole    3.3
